[platformio]
default_envs = wemos_d1_mini32

[env:wemos_d1_mini32]
platform = espressif32
board = wemos_d1_mini32
framework = arduino
extra_scripts = pre:tools/embed_dashboard.py

lib_deps =
	milesburton/DallasTemperature@^4.0.6
	adafruit/Adafruit SSD1306@^2.5.17
	adafruit/Adafruit GFX Library@^1.12.6

[env:wemos_d1_mini32_debug]
extends = env:wemos_d1_mini32
build_flags =
	-DDEBUG
monitor_speed = 115200

[env:wemos_d1_mini32_ota]
extends = env:wemos_d1_mini32
upload_protocol = espota
upload_port = cooling-controller.local

[env:native]
platform = native
test_framework = unity
test_build_src = no
