#pragma once

#include <Arduino.h>

// Generated by tools/embed_dashboard.py from web/dashboard.html.
const char kIndexHtml[] PROGMEM = R"dashboard_html(
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Cooling Controller</title>
  <style>
:root {
  color-scheme: light;
  font-family: system-ui, sans-serif;
  --bg: #f5f7f8;
  --text: #172126;
  --muted: #68787f;
  --card: #ffffff;
  --border: #dce4e7;
  --ok: #11773d;
  --bad: #bf3030;
  --demo-bg: #fff2bd;
  --demo-text: #6b4b00;
  --button: #e7eef1;
  --button-text: #172126;
  --primary: #176b4d;
  --chart-grid: #d8e1e4;
  --chart-primary: #0f7a5a;
  --chart-secondary: #b15f1b;
  --input: #ffffff;
  --overlay: rgba(12, 18, 20, 0.42);
  --shadow: 0 18px 60px rgba(21, 32, 36, 0.18);
}

[data-theme="dark"] {
  color-scheme: dark;
  --bg: #101417;
  --text: #eef4f2;
  --muted: #95a3a0;
  --card: #182024;
  --border: #2b3638;
  --ok: #65d38a;
  --bad: #ff7474;
  --demo-bg: #4a3610;
  --demo-text: #ffd979;
  --button: #283236;
  --button-text: #eef4f2;
  --chart-grid: #2e3b3e;
  --chart-primary: #5ccca1;
  --chart-secondary: #f0a45f;
  --input: #11181b;
  --overlay: rgba(0, 0, 0, 0.58);
  --shadow: 0 18px 60px rgba(0, 0, 0, 0.36);
}

body { margin: 0; background: var(--bg); color: var(--text); }
main { max-width: 860px; margin: 0 auto; padding: 22px; }
.narrow { max-width: 760px; }
header { display: flex; align-items: center; justify-content: space-between; gap: 12px; margin-bottom: 18px; }
h1 { margin: 0; font-size: 26px; font-weight: 700; }
h2 { margin: 0; font-size: 18px; }
button,
a.button,
.toolbar a {
  border: 0;
  border-radius: 8px;
  padding: 9px 12px;
  background: var(--button);
  color: var(--button-text);
  font: inherit;
  font-size: 14px;
  text-decoration: none;
}
button.primary { background: var(--primary); color: #ffffff; }
.subtle { opacity: 0.72; }
.danger { color: var(--bad); }
.actions,
.toolbar { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; justify-content: flex-end; }
.badge { border-radius: 999px; padding: 6px 9px; background: var(--demo-bg); color: var(--demo-text); font-size: 12px; font-weight: 700; text-transform: uppercase; }
.hidden { display: none; }
.grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(170px, 1fr)); gap: 10px; }
.grid.wide { grid-template-columns: repeat(auto-fit, minmax(190px, 1fr)); }
.card { border: 1px solid var(--border); border-radius: 8px; padding: 14px; background: var(--card); }
.label { color: var(--muted); font-size: 13px; }
.value { margin-top: 8px; font-size: 28px; font-weight: 700; }
.small { font-size: 18px; }
.dev-value { font-size: 22px; }
.ok { color: var(--ok); }
.bad { color: var(--bad); }
.chart-panel { margin-top: 14px; border: 1px solid var(--border); border-radius: 8px; padding: 14px; background: var(--card); }
.chart-head { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; margin-bottom: 10px; }
.chart-head h2 { margin-bottom: 4px; }
.chart-legend { display: flex; align-items: center; justify-content: flex-end; gap: 12px; flex-wrap: wrap; min-height: 22px; }
.legend-item { display: inline-flex; align-items: center; gap: 6px; color: var(--muted); font-size: 12px; font-weight: 650; }
.legend-swatch { width: 22px; height: 3px; border-radius: 999px; background: currentColor; }
.chart-wrap { position: relative; width: 100%; height: 260px; }
.chart-wrap canvas { display: block; width: 100%; height: 100%; }
.chart-empty { position: absolute; inset: 0; display: grid; place-items: center; color: var(--muted); font-size: 14px; pointer-events: none; }
.chart-empty.hidden { display: none; }
.panel { border-top: 1px solid var(--border); padding-top: 14px; margin-top: 14px; }
form { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 10px; align-items: end; }
input,
select { box-sizing: border-box; width: 100%; margin-top: 6px; border: 1px solid var(--border); border-radius: 8px; padding: 9px 10px; background: var(--input); color: var(--text); font: inherit; }
.check { display: flex; gap: 8px; align-items: center; min-height: 38px; }
.check input { width: auto; margin: 0; }
.settings-overlay { position: fixed; inset: 0; display: none; align-items: center; justify-content: center; padding: 18px; background: var(--overlay); z-index: 10; }
.settings-overlay.open { display: flex; }
.settings-dialog { width: min(620px, 100%); max-height: calc(100vh - 36px); overflow: auto; border: 1px solid var(--border); border-radius: 8px; background: var(--card); box-shadow: var(--shadow); }
.settings-head { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 14px 16px; border-bottom: 1px solid var(--border); }
#settingsForm { padding: 16px; gap: 16px; }
.settings-section { grid-column: 1 / -1; display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 10px; padding-top: 12px; border-top: 1px solid var(--border); }
.settings-section:first-child { padding-top: 0; border-top: 0; }
.section-title { grid-column: 1 / -1; margin: 0; color: var(--muted); font-size: 13px; font-weight: 700; text-transform: uppercase; }
.android-network { grid-column: 1 / -1; display: grid; gap: 10px; }
.internet-status { display: grid; grid-template-columns: 32px minmax(0, 1fr); gap: 14px; align-items: center; min-height: 56px; border-bottom: 1px solid var(--border); padding: 4px 2px 12px; }
.internet-main { min-width: 0; display: grid; gap: 2px; }
.internet-main strong { overflow-wrap: anywhere; font-size: 16px; font-weight: 650; }
.internet-main span { overflow-wrap: anywhere; color: var(--muted); font-size: 13px; }
.network-status { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 8px; }
.status-line { min-width: 0; padding: 8px 0; border-bottom: 1px solid var(--border); }
.status-line strong { display: block; color: var(--muted); font-size: 12px; font-weight: 650; }
.status-line span { display: block; margin-top: 3px; overflow-wrap: anywhere; font-size: 13px; }
.scan-panel { grid-column: 1 / -1; display: grid; gap: 6px; padding-top: 8px; }
.scan-head { display: flex; align-items: center; justify-content: space-between; gap: 10px; min-height: 42px; }
.scan-head span { display: grid; gap: 2px; }
.scan-head strong { font-size: 15px; font-weight: 650; }
.scan-head small { color: var(--muted); font-size: 12px; }
.network-list { display: grid; }
.network-item { display: grid; grid-template-columns: 32px minmax(0, 1fr) auto; gap: 14px; align-items: center; width: 100%; min-height: 58px; border: 0; border-bottom: 1px solid var(--border); border-radius: 0; padding: 8px 2px; background: transparent; color: var(--text); text-align: left; }
.network-item.selected { color: var(--primary); }
.network-main strong,
.network-main span { overflow-wrap: anywhere; }
.network-main { min-width: 0; display: grid; gap: 2px; }
.network-main strong { font-size: 15px; font-weight: 600; }
.network-main span { color: var(--muted); font-size: 12px; }
.network-trailing { min-width: 42px; color: var(--muted); font-size: 12px; text-align: right; }
.network-item.selected .network-trailing { color: var(--primary); font-weight: 650; }
.network-icon { position: relative; display: block; width: 26px; height: 24px; color: var(--muted); }
.network-icon i { position: absolute; bottom: 2px; width: 5px; border-radius: 999px; background: currentColor; opacity: 0.35; }
.network-icon i:nth-child(1) { left: 3px; height: 7px; }
.network-icon i:nth-child(2) { left: 10px; height: 13px; }
.network-icon i:nth-child(3) { left: 17px; height: 19px; }
.network-icon.signal-1 i:nth-child(1),
.network-icon.signal-2 i:nth-child(-n + 2),
.network-icon.signal-3 i { opacity: 1; }
.network-item.selected .network-icon { color: var(--primary); }
.lock-dot { display: inline-block; width: 7px; height: 7px; margin-left: 4px; border-radius: 999px; background: currentColor; opacity: 0.72; vertical-align: 1px; }
.network-details { grid-column: 1 / -1; display: grid; grid-template-columns: minmax(0, 1fr); gap: 12px; padding-top: 12px; }
.network-field { display: grid; gap: 6px; min-width: 0; padding: 0; color: var(--muted); font-size: 12px; font-weight: 650; }
.network-field input { margin: 0; border: 0; border-bottom: 1px solid var(--border); border-radius: 0; padding: 3px 0 8px; background: transparent; color: var(--text); font-size: 15px; font-weight: 500; outline: 0; }
.network-field input:focus { border-color: var(--primary); }
.network-field input::placeholder { color: var(--muted); opacity: 0.86; }
.network-field > span:last-child { color: var(--muted); font-size: 11px; font-weight: 400; }
.password-control { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 10px; align-items: end; }
.password-control button { min-width: 44px; padding: 4px 0 8px; border-radius: 0; color: var(--primary); background: transparent; font-size: 12px; font-weight: 650; }
.forget-network { justify-self: start; padding: 0; background: transparent; color: var(--bad); font-size: 13px; font-weight: 650; }
.switch-row { display: flex; align-items: center; justify-content: space-between; gap: 14px; min-height: 48px; color: var(--text); }
.switch-row strong { display: block; font-size: 14px; font-weight: 600; }
.switch-row small { display: block; margin-top: 2px; color: var(--muted); font-size: 12px; }
.switch { position: relative; width: 48px; height: 28px; flex: 0 0 auto; }
.switch input { position: absolute; inset: 0; width: 100%; height: 100%; margin: 0; opacity: 0; }
.switch span { position: absolute; inset: 0; border-radius: 999px; background: var(--border); }
.switch span::after { content: ""; position: absolute; top: 4px; left: 4px; width: 20px; height: 20px; border-radius: 50%; background: var(--card); box-shadow: 0 1px 4px rgba(0, 0, 0, 0.22); transition: transform 140ms ease; }
.switch input:checked + span { background: var(--primary); }
.switch input:checked + span::after { transform: translateX(20px); }
.form-actions { display: flex; gap: 8px; align-items: center; justify-content: flex-end; grid-column: 1 / -1; margin-top: 4px; }
#saveState { color: var(--muted); font-size: 13px; }

@media (max-width: 560px) {
  header { align-items: flex-start; flex-direction: column; }
  .actions,
  .toolbar { justify-content: flex-start; }
  .settings-overlay { align-items: flex-end; padding: 0; }
  .settings-dialog { width: 100%; max-height: 88vh; border-right: 0; border-bottom: 0; border-left: 0; }
}

  </style>
</head>
<body>
  <main class="narrow">
    <header>
      <h1>Cooling Controller</h1>
      <div class="actions">
        <span id="demoBadge" class="badge hidden">Demo scene</span>
        <span id="devBadge" class="badge hidden">Dev mode</span>
        <button id="settingsOpen" type="button">Settings</button>
        <a class="button subtle" href="/dev">Dev</a>
        <button id="themeToggle" type="button">Dark theme</button>
      </div>
    </header>
    <section class="grid">
      <div class="card"><div class="label">Temperature</div><div id="temperature" class="value">--</div></div>
      <div class="card"><div class="label">Sensor</div><div id="sensor" class="value small">--</div></div>
      <div class="card"><div class="label">Peltier</div><div id="peltier" class="value small">--</div></div>
      <div class="card"><div class="label">Fan</div><div id="fan" class="value small">--</div></div>
      <div class="card"><div class="label">Fan run-on</div><div id="runon" class="value small">--</div></div>
      <div class="card"><div class="label">Updates</div><div id="count" class="value small">--</div></div>
      <div class="card"><div class="label">Target</div><div id="target" class="value small">--</div></div>
      <div class="card"><div class="label">Uptime</div><div id="uptime" class="value small">--</div></div>
      <div class="card"><div class="label">WiFi network</div><div id="wifi" class="value small">--</div></div>
    </section>
    <section class="chart-panel" aria-labelledby="temperatureChartTitle">
      <div class="chart-head">
        <div>
          <h2 id="temperatureChartTitle">Temperature history</h2>
          <div id="chartWindow" class="label">Last 30 min</div>
        </div>
        <div id="chartLegend" class="chart-legend"></div>
      </div>
      <div class="chart-wrap">
        <canvas id="temperatureChart" height="260" aria-label="Temperature over time"></canvas>
        <div id="chartEmpty" class="chart-empty">Waiting for measurements</div>
      </div>
    </section>
  </main>
  <div id="settingsOverlay" class="settings-overlay" role="dialog" aria-modal="true" aria-labelledby="settingsTitle">
    <section class="settings-dialog">
      <div class="settings-head">
        <h2 id="settingsTitle">Control settings</h2>
        <button id="settingsClose" type="button">Close</button>
      </div>
      <form id="settingsForm">
        <section class="settings-section">
          <h3 class="section-title">Cooling</h3>
          <label class="label">Target, C<input id="targetInput" name="targetC" type="number" min="-20" max="40" step="0.1" required></label>
          <label class="label">Hysteresis, C<input id="hysteresisInput" name="hysteresisC" type="number" min="0.1" max="10" step="0.1" required></label>
          <label class="label">Measurement, ms<input id="measurementInput" name="measurementIntervalMs" type="number" min="250" max="60000" step="50" required></label>
          <label class="label">Fan run-on, ms<input id="fanRunOnInput" name="fanRunOnMs" type="number" min="0" max="600000" step="1000" required></label>
        </section>
        <section class="settings-section">
          <h3 class="section-title">Network</h3>
          <div class="android-network">
            <div class="internet-status">
              <span class="network-icon signal-3" aria-hidden="true"><i></i><i></i><i></i></span>
              <span class="internet-main">
                <strong id="stationStatus">--</strong>
                <span id="stationPageStatus">--</span>
              </span>
            </div>
            <div class="network-status">
              <div class="status-line"><strong>Device hotspot</strong><span id="apStatus">--</span></div>
              <div class="status-line"><strong>Hotspot page</strong><span id="apPageStatus">--</span></div>
              <div class="status-line"><strong>Current page</strong><span id="currentPageStatus">--</span></div>
            </div>
          </div>
          <div class="scan-panel">
            <div class="scan-head">
              <span>
                <strong>Available networks</strong>
                <small id="networkScanState">Not scanned yet</small>
              </span>
              <button id="scanNetworks" type="button">Refresh</button>
            </div>
            <div id="networkList" class="network-list" aria-live="polite"></div>
          </div>
          <div class="network-details">
            <label class="network-field">Network name<input id="stationSsidInput" name="stationSsid" type="text" maxlength="32" autocomplete="off" placeholder="Select a network" readonly><span>Select from the list or enable hidden network</span></label>
            <label class="network-field password-field">Password<span class="password-control"><input id="stationPasswordInput" name="stationPassword" type="password" maxlength="64" autocomplete="new-password" placeholder="Leave blank to keep saved"><button id="toggleStationPassword" type="button" aria-pressed="false">Show</button></span><span>Leave blank to keep the saved password</span></label>
            <label class="switch-row">
              <span><strong>Hidden network</strong><small>Manual SSID</small></span>
              <span class="switch"><input id="hiddenNetworkInput" name="hiddenNetwork" type="checkbox" value="1"><span></span></span>
            </label>
            <input id="forgetStationNetworkInput" name="forgetStationNetwork" type="hidden" value="0">
            <button id="forgetStationNetwork" class="forget-network" type="button">Forget network</button>
          </div>
        </section>
        <div class="form-actions">
          <span id="saveState"></span>
          <button class="primary" type="submit">Save</button>
        </div>
      </form>
    </section>
  </div>
  <script>
(function () {
  const storageKeys = {
    theme: 'cooling-dashboard.theme',
    legacyTheme: 'theme',
    devState: 'cooling-dashboard.devState'
  };
  const defaultDevState = {
    ok: true,
    enabled: false,
    temperatureC: 5.0,
    hasTemperature: true,
    sensorDisconnected: false,
    updateCount: 0,
    peltierRunning: false,
    fanRunning: false,
    fanRunOnActive: false,
    fanRunOnRemainingMs: 0
  };
  const setText = (id, text) => document.getElementById(id).textContent = text;
  const readStoredDevState = () => {
    try {
      return { ...defaultDevState, ...JSON.parse(localStorage.getItem(storageKeys.devState) || '{}') };
    } catch (error) {
      return { ...defaultDevState };
    }
  };
  const storeDevState = (data) => {
    localStorage.setItem(storageKeys.devState, JSON.stringify({ ...defaultDevState, ...data }));
  };
  const initTheme = () => {
    const themeToggle = document.getElementById('themeToggle');
    if (!themeToggle) return;
    const applyTheme = (theme) => {
      document.documentElement.dataset.theme = theme;
      themeToggle.textContent = theme === 'dark' ? 'Light theme' : 'Dark theme';
      localStorage.setItem(storageKeys.theme, theme);
      localStorage.setItem(storageKeys.legacyTheme, theme);
    };
    applyTheme(localStorage.getItem(storageKeys.theme) || localStorage.getItem(storageKeys.legacyTheme) || 'light');
    themeToggle.addEventListener('click', () => {
      applyTheme(document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark');
    });
  };
  window.CoolingWeb = {
    storageKeys,
    defaultDevState,
    initTheme,
    readStoredDevState,
    storeDevState,
    setText
  };
  document.addEventListener('DOMContentLoaded', initTheme);
}());

  </script>
  <script>
(function () {
  const { readStoredDevState, setText } = window.CoolingWeb;
  const startedAt = Date.now();
  const chartHistoryMs = 30 * 60 * 1000;
  const temperatureSeries = [
    {
      id: 'probe1',
      label: 'Probe 1',
      valueKey: 'temperatureC',
      hasKey: 'hasTemperature',
      invalidKey: 'sensorDisconnected',
      updateCountKey: 'updateCount',
      colorVar: '--chart-primary',
      primary: true
    },
    {
      id: 'probe2',
      label: 'Probe 2',
      valueKey: 'secondaryTemperatureC',
      hasKey: 'hasSecondaryTemperature',
      invalidKey: 'secondarySensorDisconnected',
      updateCountKey: 'secondaryUpdateCount',
      colorVar: '--chart-secondary'
    }
  ];
  const chartSamples = new Map(temperatureSeries.map((series) => [series.id, []]));
  const lastChartSampleKeys = new Map();
  let lastChartUptimeMs = 0;
  const setState = (id, on) => {
    const el = document.getElementById(id);
    el.textContent = on ? 'ON' : 'OFF';
    el.className = 'value small ' + (on ? 'ok' : '');
  };
  const isSeriesAvailable = (series, data) => (
    series.primary || Object.prototype.hasOwnProperty.call(data, series.valueKey)
  );
  const hasValidSeriesValue = (series, data) => {
    const value = Number(data[series.valueKey]);
    const hasValue = series.hasKey ? Boolean(data[series.hasKey]) : Number.isFinite(value);
    const invalid = series.invalidKey ? Boolean(data[series.invalidKey]) : false;
    return hasValue && !invalid && Number.isFinite(value);
  };
  const sampleTimeMs = (data) => {
    const uptimeMs = Number(data.uptimeMs);
    return Number.isFinite(uptimeMs) ? uptimeMs : Date.now() - startedAt;
  };
  const trimChartSamples = (samples, latestTimeMs) => {
    const cutoffMs = latestTimeMs - chartHistoryMs;
    while (samples.length && samples[0].timeMs < cutoffMs) {
      samples.shift();
    }
  };
  const addSeriesSample = (series, timeMs, value) => {
    const samples = chartSamples.get(series.id);
    if (!samples || !Number.isFinite(timeMs) || !Number.isFinite(value)) return;
    if (samples.some((sample) => sample.timeMs === timeMs)) return;
    samples.push({ timeMs, value });
    samples.sort((left, right) => left.timeMs - right.timeMs);
    trimChartSamples(samples, Math.max(timeMs, lastChartUptimeMs));
  };
  const addChartSample = (data) => {
    const timeMs = sampleTimeMs(data);
    if (timeMs + 1000 < lastChartUptimeMs) {
      chartSamples.forEach((samples) => samples.splice(0, samples.length));
      lastChartSampleKeys.clear();
    }
    lastChartUptimeMs = timeMs;

    temperatureSeries.forEach((series) => {
      if (!isSeriesAvailable(series, data)) return;
      const samples = chartSamples.get(series.id);
      const count = series.updateCountKey && data[series.updateCountKey] !== undefined
        ? data[series.updateCountKey]
        : Math.floor(timeMs / 1000);
      const sampleKey = String(count) + ':' + String(data[series.valueKey]);
      if (lastChartSampleKeys.get(series.id) === sampleKey) return;
      lastChartSampleKeys.set(series.id, sampleKey);
      if (hasValidSeriesValue(series, data)) {
        addSeriesSample(series, timeMs, Number(data[series.valueKey]));
      } else {
        trimChartSamples(samples, timeMs);
      }
    });
  };
  const applyHistory = (history) => {
    if (!history || !Array.isArray(history.series)) return;
    history.series.forEach((remoteSeries) => {
      const series = temperatureSeries.find((item) => item.id === remoteSeries.id);
      if (!series || !Array.isArray(remoteSeries.points)) return;
      remoteSeries.points.forEach((point) => {
        if (!Array.isArray(point) || point.length < 2) return;
        const flags = Number(point[2]) || 0;
        if ((flags & 1) !== 0) return;
        addSeriesSample(series, Number(point[0]), Number(point[1]) / 10);
      });
    });
  };
  const loadHistory = async () => {
    try {
      const res = await fetch('/api/history', { cache: 'no-store' });
      if (!res.ok) throw new Error('history unavailable');
      applyHistory(await res.json());
      drawTemperatureChart();
    } catch (error) {
      // History is optional; live samples will continue filling the chart.
    }
  };
  const formatAgo = (ms) => {
    const minutes = Math.max(0, Math.round(ms / 60000));
    return minutes <= 0 ? 'now' : '-' + minutes + ' min';
  };
  const chartColors = (canvas, series) => {
    const style = getComputedStyle(document.documentElement);
    return {
      text: style.getPropertyValue('--muted').trim(),
      grid: style.getPropertyValue('--chart-grid').trim(),
      line: style.getPropertyValue(series.colorVar).trim()
    };
  };
  const renderChartLegend = (legend) => {
    legend.textContent = '';
    temperatureSeries.filter((series) => chartSamples.get(series.id).length > 0).forEach((series) => {
      const item = document.createElement('span');
      item.className = 'legend-item';
      item.style.color = getComputedStyle(document.documentElement).getPropertyValue(series.colorVar).trim();
      const swatch = document.createElement('span');
      swatch.className = 'legend-swatch';
      const label = document.createElement('span');
      label.textContent = series.label;
      item.append(swatch, label);
      legend.append(item);
    });
  };
  const drawTemperatureChart = () => {
    const canvas = document.getElementById('temperatureChart');
    const empty = document.getElementById('chartEmpty');
    const legend = document.getElementById('chartLegend');
    if (!canvas || !empty || !legend) return;

    const allSamples = temperatureSeries.flatMap((series) => chartSamples.get(series.id));
    empty.classList.toggle('hidden', allSamples.length > 0);
    renderChartLegend(legend);

    const rect = canvas.getBoundingClientRect();
    const dpr = window.devicePixelRatio || 1;
    const width = Math.max(1, Math.round(rect.width * dpr));
    const height = Math.max(1, Math.round(rect.height * dpr));
    if (canvas.width !== width || canvas.height !== height) {
      canvas.width = width;
      canvas.height = height;
    }

    const ctx = canvas.getContext('2d');
    ctx.clearRect(0, 0, width, height);
    if (!allSamples.length) return;

    const nowMs = Math.max(...allSamples.map((sample) => sample.timeMs));
    const startMs = Math.max(0, nowMs - chartHistoryMs);
    const minValue = Math.min(...allSamples.map((sample) => sample.value));
    const maxValue = Math.max(...allSamples.map((sample) => sample.value));
    const valuePadding = Math.max(0.5, (maxValue - minValue) * 0.18);
    const yMin = Math.floor((minValue - valuePadding) * 2) / 2;
    const yMax = Math.ceil((maxValue + valuePadding) * 2) / 2;
    const span = Math.max(1, yMax - yMin);
    const pad = {
      left: 42 * dpr,
      right: 10 * dpr,
      top: 12 * dpr,
      bottom: 28 * dpr
    };
    const plotW = Math.max(1, width - pad.left - pad.right);
    const plotH = Math.max(1, height - pad.top - pad.bottom);
    const axisColor = chartColors(canvas, temperatureSeries[0]);
    const xFor = (timeMs) => pad.left + ((timeMs - startMs) / chartHistoryMs) * plotW;
    const yFor = (value) => pad.top + (1 - ((value - yMin) / span)) * plotH;

    ctx.font = String(11 * dpr) + 'px system-ui, sans-serif';
    ctx.lineWidth = 1 * dpr;
    ctx.strokeStyle = axisColor.grid;
    ctx.fillStyle = axisColor.text;
    ctx.textBaseline = 'middle';

    for (let i = 0; i <= 4; i += 1) {
      const y = pad.top + (plotH / 4) * i;
      const value = yMax - (span / 4) * i;
      ctx.beginPath();
      ctx.moveTo(pad.left, y);
      ctx.lineTo(width - pad.right, y);
      ctx.stroke();
      ctx.textAlign = 'right';
      ctx.fillText(value.toFixed(1), pad.left - 8 * dpr, y);
    }

    ctx.textBaseline = 'top';
    for (let i = 0; i <= 3; i += 1) {
      const x = pad.left + (plotW / 3) * i;
      const ageMs = chartHistoryMs - (chartHistoryMs / 3) * i;
      ctx.beginPath();
      ctx.moveTo(x, pad.top);
      ctx.lineTo(x, pad.top + plotH);
      ctx.stroke();
      ctx.textAlign = i === 0 ? 'left' : (i === 3 ? 'right' : 'center');
      ctx.fillText(formatAgo(ageMs), x, pad.top + plotH + 8 * dpr);
    }

    temperatureSeries.forEach((series) => {
      const samples = chartSamples.get(series.id).filter((sample) => sample.timeMs >= startMs);
      if (!samples.length) return;
      ctx.strokeStyle = chartColors(canvas, series).line;
      ctx.lineWidth = 2 * dpr;
      ctx.beginPath();
      samples.forEach((sample, index) => {
        const x = xFor(sample.timeMs);
        const y = yFor(sample.value);
        if (index === 0) ctx.moveTo(x, y);
        else ctx.lineTo(x, y);
      });
      ctx.stroke();
    });
  };
  const mockStatus = () => {
    const elapsedMs = Date.now() - startedAt;
    const peltierRunning = Math.floor(elapsedMs / 7000) % 2 === 0;
    return {
      temperatureC: 5.4 + Math.sin(elapsedMs / 3500) * 0.8,
      hasTemperature: true,
      sensorDisconnected: false,
      updateCount: Math.floor(elapsedMs / 1000),
      peltierRunning,
      fanRunning: peltierRunning || Math.floor(elapsedMs / 3000) % 5 === 0,
      fanRunOnActive: !peltierRunning && Math.floor(elapsedMs / 3000) % 5 === 0,
      fanRunOnRemainingMs: 12000 - (elapsedMs % 12000),
      targetC: 5.0,
      hysteresisC: 0.1,
      measurementIntervalMs: 500,
      fanRunOnMs: 30000,
      uptimeMs: elapsedMs,
      accessPointSsid: 'CoolingController',
      accessPointIp: '',
      stationSsid: '',
      stationPasswordSet: false,
      stationConnected: false,
      stationStatus: 'disabled',
      stationIp: '',
      stationRssi: 0,
      devMode: false,
      demo: true
    };
  };
  const mockFromDevState = (devState, elapsedMs) => ({
    temperatureC: Number(devState.temperatureC) || 0,
    hasTemperature: Boolean(devState.hasTemperature),
    sensorDisconnected: Boolean(devState.sensorDisconnected),
    updateCount: Number(devState.updateCount) || 0,
    peltierRunning: Boolean(devState.peltierRunning),
    fanRunning: Boolean(devState.fanRunning),
    fanRunOnActive: Boolean(devState.fanRunOnActive),
    fanRunOnRemainingMs: Number(devState.fanRunOnRemainingMs) || 0,
    targetC: 5.0,
    hysteresisC: 0.1,
    measurementIntervalMs: 500,
    fanRunOnMs: 30000,
    uptimeMs: elapsedMs,
    accessPointSsid: 'CoolingController',
    accessPointIp: '',
    stationSsid: '',
    stationPasswordSet: false,
    stationConnected: false,
    stationStatus: 'disabled',
    stationIp: '',
    stationRssi: 0,
    devMode: true,
    demo: true
  });
  const pageUrl = (ip) => ip ? 'http://' + ip + '/' : '--';
  const signalQuality = (rssi) => {
    if (rssi >= -55) return 'Excellent';
    if (rssi >= -67) return 'Good';
    if (rssi >= -75) return 'Fair';
    return 'Weak';
  };
  const signalLevel = (rssi) => {
    const value = Number(rssi);
    if (value >= -60) return 3;
    if (value >= -72) return 2;
    return 1;
  };

  document.addEventListener('DOMContentLoaded', () => {
    const demoBadge = document.getElementById('demoBadge');
    const devBadge = document.getElementById('devBadge');
    const settingsForm = document.getElementById('settingsForm');
    const settingsOverlay = document.getElementById('settingsOverlay');
    const settingsOpen = document.getElementById('settingsOpen');
    const settingsClose = document.getElementById('settingsClose');
    const scanNetworks = document.getElementById('scanNetworks');
    const networkList = document.getElementById('networkList');
    const networkScanState = document.getElementById('networkScanState');
    const saveState = document.getElementById('saveState');
    const stationSsidInput = document.getElementById('stationSsidInput');
    const stationPasswordInput = document.getElementById('stationPasswordInput');
    const toggleStationPassword = document.getElementById('toggleStationPassword');
    const hiddenNetworkInput = document.getElementById('hiddenNetworkInput');
    const forgetStationNetworkInput = document.getElementById('forgetStationNetworkInput');
    const forgetStationNetwork = document.getElementById('forgetStationNetwork');
    let settingsDirty = false;
    let networkScanStartedAt = 0;
    let currentSavedStationSsid = '';
    let selectedNetworkSsid = '';
    let visibleNetworkSsids = new Set();
    const setHiddenNetworkMode = (enabled, keepValue) => {
      hiddenNetworkInput.checked = enabled;
      stationSsidInput.readOnly = !enabled;
      stationSsidInput.placeholder = enabled ? 'Enter hidden network SSID' : 'Select from nearby networks';
      if (enabled) {
        selectedNetworkSsid = '';
        if (!keepValue) stationSsidInput.value = '';
      }
      if (!enabled && selectedNetworkSsid) {
        stationSsidInput.value = selectedNetworkSsid;
      }
    };
    const applySettingsToForm = (data) => {
      if (settingsDirty) return;
      document.getElementById('targetInput').value = Number(data.targetC).toFixed(1);
      document.getElementById('hysteresisInput').value = Number(data.hysteresisC).toFixed(1);
      document.getElementById('measurementInput').value = data.measurementIntervalMs;
      document.getElementById('fanRunOnInput').value = data.fanRunOnMs;
      currentSavedStationSsid = data.stationSsid || '';
      selectedNetworkSsid = currentSavedStationSsid;
      stationSsidInput.value = currentSavedStationSsid;
      stationPasswordInput.value = '';
      stationPasswordInput.type = 'password';
      toggleStationPassword.textContent = 'Show';
      toggleStationPassword.setAttribute('aria-pressed', 'false');
      stationPasswordInput.placeholder = data.stationPasswordSet ? 'Saved; leave blank to keep' : 'Leave blank for open network';
      forgetStationNetworkInput.value = '0';
      setHiddenNetworkMode(false, true);
    };
    const renderNetworkStatus = (data) => {
      setText('apStatus', data.accessPointSsid || '--');
      setText('apPageStatus', pageUrl(data.accessPointIp));
      setText('stationStatus', data.stationSsid ? data.stationSsid : (data.stationLastFailure ? 'Failed' : 'Not connected'));
      setText('stationPageStatus', data.stationConnected ? pageUrl(data.stationIp) : (data.stationSsid ? (data.stationStatus || 'disconnected') : 'Wi-Fi off'));
      setText('currentPageStatus', window.location.origin || '--');
    };
    const renderNetworks = (networks) => {
      networkList.textContent = '';
      visibleNetworkSsids = new Set();
      if (!networks.length) {
        networkScanState.textContent = 'No 2.4 GHz networks found';
        return;
      }
      networkScanState.textContent = networks.length + ' found';
      networks.forEach((network) => {
        if (network.ssid) visibleNetworkSsids.add(network.ssid);
        const item = document.createElement('button');
        item.type = 'button';
        item.className = 'network-item';
        const selected = Boolean(network.ssid) && network.ssid === stationSsidInput.value && !hiddenNetworkInput.checked;
        item.classList.toggle('selected', selected);
        item.addEventListener('click', () => {
          if (network.ssid) {
            selectedNetworkSsid = network.ssid;
            forgetStationNetworkInput.value = '0';
            setHiddenNetworkMode(false, false);
          } else {
            forgetStationNetworkInput.value = '0';
            setHiddenNetworkMode(true, false);
            stationSsidInput.focus();
          }
          renderNetworks(networks);
          settingsDirty = true;
          saveState.textContent = '';
        });

        const icon = document.createElement('span');
        icon.className = 'network-icon signal-' + signalLevel(network.rssi);
        icon.setAttribute('aria-hidden', 'true');
        icon.append(document.createElement('i'), document.createElement('i'), document.createElement('i'));

        const main = document.createElement('span');
        main.className = 'network-main';
        const ssid = document.createElement('strong');
        ssid.textContent = network.ssid || '(hidden network)';
        const detail = document.createElement('span');
        detail.textContent = [
          signalQuality(Number(network.rssi)),
          Number(network.rssi) + ' dBm',
          'ch ' + network.channel,
          network.encrypted ? 'secured' : 'open'
        ].join(' / ');
        main.append(ssid, detail);

        const trailing = document.createElement('span');
        trailing.className = 'network-trailing';
        trailing.textContent = selected ? 'Selected' : (network.encrypted ? 'Secured' : '');
        if (network.encrypted && !selected) {
          const lock = document.createElement('span');
          lock.className = 'lock-dot';
          trailing.append(lock);
        }
        item.append(icon, main, trailing);
        networkList.append(item);
      });
    };
    const loadNetworks = async (polling) => {
      if (!polling) {
        networkScanStartedAt = Date.now();
      }
      scanNetworks.disabled = true;
      networkScanState.textContent = polling ? 'Still scanning...' : 'Scanning...';
      try {
        const res = await fetch('/api/networks', { cache: 'no-store' });
        if (!res.ok) throw new Error('scan unavailable');
        const data = await res.json();
        if (data.scanStatus === 'scanning') {
          if (Date.now() - networkScanStartedAt > 15000) {
            networkList.textContent = '';
            networkScanState.textContent = 'Scan timeout';
            return;
          }
          window.setTimeout(() => loadNetworks(true), 600);
          return;
        }
        if (!data.ok) {
          networkList.textContent = '';
          networkScanState.textContent = 'Scan ' + (data.scanStatus || 'failed');
          return;
        }
        renderNetworks(Array.isArray(data.networks) ? data.networks : []);
      } catch (error) {
        renderNetworks([
          { ssid: 'Kitchen WiFi', rssi: -48, channel: 6, encrypted: true },
          { ssid: 'Workshop', rssi: -66, channel: 11, encrypted: true },
          { ssid: 'Guest', rssi: -78, channel: 1, encrypted: false }
        ]);
        networkScanState.textContent = 'Demo scan';
      } finally {
        if (networkScanState.textContent !== 'Still scanning...' && networkScanState.textContent !== 'Scanning...') {
          scanNetworks.disabled = false;
        }
      }
    };
    const openSettings = () => {
      settingsOverlay.classList.add('open');
      settingsOpen.setAttribute('aria-expanded', 'true');
      document.getElementById('targetInput').focus();
    };
    const closeSettings = () => {
      settingsOverlay.classList.remove('open');
      settingsOpen.setAttribute('aria-expanded', 'false');
      settingsOpen.focus();
    };
    settingsOpen.setAttribute('aria-expanded', 'false');
    settingsOpen.addEventListener('click', openSettings);
    settingsClose.addEventListener('click', closeSettings);
    scanNetworks.addEventListener('click', () => loadNetworks(false));
    toggleStationPassword.addEventListener('click', () => {
      const showing = stationPasswordInput.type === 'text';
      stationPasswordInput.type = showing ? 'password' : 'text';
      toggleStationPassword.textContent = showing ? 'Show' : 'Hide';
      toggleStationPassword.setAttribute('aria-pressed', showing ? 'false' : 'true');
      stationPasswordInput.focus();
    });
    hiddenNetworkInput.addEventListener('change', () => {
      forgetStationNetworkInput.value = '0';
      setHiddenNetworkMode(hiddenNetworkInput.checked, true);
      settingsDirty = true;
      saveState.textContent = '';
      if (hiddenNetworkInput.checked) stationSsidInput.focus();
    });
    forgetStationNetwork.addEventListener('click', () => {
      selectedNetworkSsid = '';
      stationSsidInput.value = '';
      stationPasswordInput.value = '';
      forgetStationNetworkInput.value = '1';
      setHiddenNetworkMode(false, true);
      settingsDirty = true;
      saveState.textContent = 'Network will be forgotten on save';
    });
    settingsOverlay.addEventListener('click', (event) => {
      if (event.target === settingsOverlay) closeSettings();
    });
    document.addEventListener('keydown', (event) => {
      if (event.key === 'Escape' && settingsOverlay.classList.contains('open')) closeSettings();
    });
    async function loadStatus() {
      try {
        const res = await fetch('/api/status', { cache: 'no-store' });
        if (!res.ok) throw new Error('status unavailable');
        const data = await res.json();
        data.demo = false;
        return data;
      } catch (error) {
        const devState = readStoredDevState();
        return devState.enabled ? mockFromDevState(devState, Date.now() - startedAt) : mockStatus();
      }
    }
    async function refresh() {
      const data = await loadStatus();
      addChartSample(data);
      demoBadge.classList.toggle('hidden', !data.demo);
      devBadge.classList.toggle('hidden', !data.devMode);
      setText('temperature', data.hasTemperature ? data.temperatureC.toFixed(1) + ' C' : '--');
      const sensor = document.getElementById('sensor');
      sensor.textContent = data.sensorDisconnected ? 'ERROR' : 'OK';
      sensor.className = 'value small ' + (data.sensorDisconnected ? 'bad' : 'ok');
      setState('peltier', data.peltierRunning);
      setState('fan', data.fanRunning);
      setText('runon', data.fanRunOnActive ? Math.ceil(data.fanRunOnRemainingMs / 1000) + ' s' : 'OFF');
      setText('count', data.updateCount);
      setText('target', data.targetC.toFixed(1) + ' C / hys ' + data.hysteresisC.toFixed(1));
      setText('uptime', Math.floor(data.uptimeMs / 1000) + ' s');
      setText('wifi', data.stationSsid ? (data.stationConnected ? data.stationIp : (data.stationStatus || 'Disconnected')) : (data.stationLastFailure ? 'Failed: ' + data.stationLastFailure : 'Disabled'));
      renderNetworkStatus(data);
      applySettingsToForm(data);
      drawTemperatureChart();
    }
    settingsForm.addEventListener('input', () => {
      settingsDirty = true;
      saveState.textContent = '';
    });
    settingsForm.addEventListener('submit', async (event) => {
      event.preventDefault();
      stationSsidInput.value = stationSsidInput.value.trim();
      const stationSsidChanged = stationSsidInput.value !== currentSavedStationSsid;
      if (!hiddenNetworkInput.checked &&
          stationSsidChanged &&
          stationSsidInput.value.length > 0 &&
          !visibleNetworkSsids.has(stationSsidInput.value)) {
        saveState.textContent = 'Scan and select a network first';
        return;
      }
      if (hiddenNetworkInput.checked && stationSsidInput.value.length === 0) {
        saveState.textContent = 'Enter hidden network SSID';
        stationSsidInput.focus();
        return;
      }
      saveState.textContent = 'Saving...';
      try {
        const body = new URLSearchParams(new FormData(settingsForm));
        const res = await fetch('/api/settings', {
          method: 'POST',
          headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
          body
        });
        if (!res.ok) throw new Error('save failed');
        const data = await res.json();
        settingsDirty = false;
        applySettingsToForm(data);
        saveState.textContent = 'Saved';
        await refresh();
      } catch (error) {
        saveState.textContent = 'Save failed';
      }
    });
    window.addEventListener('resize', drawTemperatureChart);
    document.getElementById('themeToggle').addEventListener('click', () => {
      window.setTimeout(drawTemperatureChart, 0);
    });
    loadHistory();
    refresh();
    setInterval(refresh, 1000);
  });
}());

  </script>
</body>
</html>

)dashboard_html";

// Generated by tools/embed_dashboard.py from web/dev.html.
const char kDevHtml[] PROGMEM = R"dev_html(
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Cooling Controller Dev</title>
  <style>
:root {
  color-scheme: light;
  font-family: system-ui, sans-serif;
  --bg: #f5f7f8;
  --text: #172126;
  --muted: #68787f;
  --card: #ffffff;
  --border: #dce4e7;
  --ok: #11773d;
  --bad: #bf3030;
  --demo-bg: #fff2bd;
  --demo-text: #6b4b00;
  --button: #e7eef1;
  --button-text: #172126;
  --primary: #176b4d;
  --chart-grid: #d8e1e4;
  --chart-primary: #0f7a5a;
  --chart-secondary: #b15f1b;
  --input: #ffffff;
  --overlay: rgba(12, 18, 20, 0.42);
  --shadow: 0 18px 60px rgba(21, 32, 36, 0.18);
}

[data-theme="dark"] {
  color-scheme: dark;
  --bg: #101417;
  --text: #eef4f2;
  --muted: #95a3a0;
  --card: #182024;
  --border: #2b3638;
  --ok: #65d38a;
  --bad: #ff7474;
  --demo-bg: #4a3610;
  --demo-text: #ffd979;
  --button: #283236;
  --button-text: #eef4f2;
  --chart-grid: #2e3b3e;
  --chart-primary: #5ccca1;
  --chart-secondary: #f0a45f;
  --input: #11181b;
  --overlay: rgba(0, 0, 0, 0.58);
  --shadow: 0 18px 60px rgba(0, 0, 0, 0.36);
}

body { margin: 0; background: var(--bg); color: var(--text); }
main { max-width: 860px; margin: 0 auto; padding: 22px; }
.narrow { max-width: 760px; }
header { display: flex; align-items: center; justify-content: space-between; gap: 12px; margin-bottom: 18px; }
h1 { margin: 0; font-size: 26px; font-weight: 700; }
h2 { margin: 0; font-size: 18px; }
button,
a.button,
.toolbar a {
  border: 0;
  border-radius: 8px;
  padding: 9px 12px;
  background: var(--button);
  color: var(--button-text);
  font: inherit;
  font-size: 14px;
  text-decoration: none;
}
button.primary { background: var(--primary); color: #ffffff; }
.subtle { opacity: 0.72; }
.danger { color: var(--bad); }
.actions,
.toolbar { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; justify-content: flex-end; }
.badge { border-radius: 999px; padding: 6px 9px; background: var(--demo-bg); color: var(--demo-text); font-size: 12px; font-weight: 700; text-transform: uppercase; }
.hidden { display: none; }
.grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(170px, 1fr)); gap: 10px; }
.grid.wide { grid-template-columns: repeat(auto-fit, minmax(190px, 1fr)); }
.card { border: 1px solid var(--border); border-radius: 8px; padding: 14px; background: var(--card); }
.label { color: var(--muted); font-size: 13px; }
.value { margin-top: 8px; font-size: 28px; font-weight: 700; }
.small { font-size: 18px; }
.dev-value { font-size: 22px; }
.ok { color: var(--ok); }
.bad { color: var(--bad); }
.chart-panel { margin-top: 14px; border: 1px solid var(--border); border-radius: 8px; padding: 14px; background: var(--card); }
.chart-head { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; margin-bottom: 10px; }
.chart-head h2 { margin-bottom: 4px; }
.chart-legend { display: flex; align-items: center; justify-content: flex-end; gap: 12px; flex-wrap: wrap; min-height: 22px; }
.legend-item { display: inline-flex; align-items: center; gap: 6px; color: var(--muted); font-size: 12px; font-weight: 650; }
.legend-swatch { width: 22px; height: 3px; border-radius: 999px; background: currentColor; }
.chart-wrap { position: relative; width: 100%; height: 260px; }
.chart-wrap canvas { display: block; width: 100%; height: 100%; }
.chart-empty { position: absolute; inset: 0; display: grid; place-items: center; color: var(--muted); font-size: 14px; pointer-events: none; }
.chart-empty.hidden { display: none; }
.panel { border-top: 1px solid var(--border); padding-top: 14px; margin-top: 14px; }
form { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 10px; align-items: end; }
input,
select { box-sizing: border-box; width: 100%; margin-top: 6px; border: 1px solid var(--border); border-radius: 8px; padding: 9px 10px; background: var(--input); color: var(--text); font: inherit; }
.check { display: flex; gap: 8px; align-items: center; min-height: 38px; }
.check input { width: auto; margin: 0; }
.settings-overlay { position: fixed; inset: 0; display: none; align-items: center; justify-content: center; padding: 18px; background: var(--overlay); z-index: 10; }
.settings-overlay.open { display: flex; }
.settings-dialog { width: min(620px, 100%); max-height: calc(100vh - 36px); overflow: auto; border: 1px solid var(--border); border-radius: 8px; background: var(--card); box-shadow: var(--shadow); }
.settings-head { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 14px 16px; border-bottom: 1px solid var(--border); }
#settingsForm { padding: 16px; gap: 16px; }
.settings-section { grid-column: 1 / -1; display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 10px; padding-top: 12px; border-top: 1px solid var(--border); }
.settings-section:first-child { padding-top: 0; border-top: 0; }
.section-title { grid-column: 1 / -1; margin: 0; color: var(--muted); font-size: 13px; font-weight: 700; text-transform: uppercase; }
.android-network { grid-column: 1 / -1; display: grid; gap: 10px; }
.internet-status { display: grid; grid-template-columns: 32px minmax(0, 1fr); gap: 14px; align-items: center; min-height: 56px; border-bottom: 1px solid var(--border); padding: 4px 2px 12px; }
.internet-main { min-width: 0; display: grid; gap: 2px; }
.internet-main strong { overflow-wrap: anywhere; font-size: 16px; font-weight: 650; }
.internet-main span { overflow-wrap: anywhere; color: var(--muted); font-size: 13px; }
.network-status { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 8px; }
.status-line { min-width: 0; padding: 8px 0; border-bottom: 1px solid var(--border); }
.status-line strong { display: block; color: var(--muted); font-size: 12px; font-weight: 650; }
.status-line span { display: block; margin-top: 3px; overflow-wrap: anywhere; font-size: 13px; }
.scan-panel { grid-column: 1 / -1; display: grid; gap: 6px; padding-top: 8px; }
.scan-head { display: flex; align-items: center; justify-content: space-between; gap: 10px; min-height: 42px; }
.scan-head span { display: grid; gap: 2px; }
.scan-head strong { font-size: 15px; font-weight: 650; }
.scan-head small { color: var(--muted); font-size: 12px; }
.network-list { display: grid; }
.network-item { display: grid; grid-template-columns: 32px minmax(0, 1fr) auto; gap: 14px; align-items: center; width: 100%; min-height: 58px; border: 0; border-bottom: 1px solid var(--border); border-radius: 0; padding: 8px 2px; background: transparent; color: var(--text); text-align: left; }
.network-item.selected { color: var(--primary); }
.network-main strong,
.network-main span { overflow-wrap: anywhere; }
.network-main { min-width: 0; display: grid; gap: 2px; }
.network-main strong { font-size: 15px; font-weight: 600; }
.network-main span { color: var(--muted); font-size: 12px; }
.network-trailing { min-width: 42px; color: var(--muted); font-size: 12px; text-align: right; }
.network-item.selected .network-trailing { color: var(--primary); font-weight: 650; }
.network-icon { position: relative; display: block; width: 26px; height: 24px; color: var(--muted); }
.network-icon i { position: absolute; bottom: 2px; width: 5px; border-radius: 999px; background: currentColor; opacity: 0.35; }
.network-icon i:nth-child(1) { left: 3px; height: 7px; }
.network-icon i:nth-child(2) { left: 10px; height: 13px; }
.network-icon i:nth-child(3) { left: 17px; height: 19px; }
.network-icon.signal-1 i:nth-child(1),
.network-icon.signal-2 i:nth-child(-n + 2),
.network-icon.signal-3 i { opacity: 1; }
.network-item.selected .network-icon { color: var(--primary); }
.lock-dot { display: inline-block; width: 7px; height: 7px; margin-left: 4px; border-radius: 999px; background: currentColor; opacity: 0.72; vertical-align: 1px; }
.network-details { grid-column: 1 / -1; display: grid; grid-template-columns: minmax(0, 1fr); gap: 12px; padding-top: 12px; }
.network-field { display: grid; gap: 6px; min-width: 0; padding: 0; color: var(--muted); font-size: 12px; font-weight: 650; }
.network-field input { margin: 0; border: 0; border-bottom: 1px solid var(--border); border-radius: 0; padding: 3px 0 8px; background: transparent; color: var(--text); font-size: 15px; font-weight: 500; outline: 0; }
.network-field input:focus { border-color: var(--primary); }
.network-field input::placeholder { color: var(--muted); opacity: 0.86; }
.network-field > span:last-child { color: var(--muted); font-size: 11px; font-weight: 400; }
.password-control { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 10px; align-items: end; }
.password-control button { min-width: 44px; padding: 4px 0 8px; border-radius: 0; color: var(--primary); background: transparent; font-size: 12px; font-weight: 650; }
.forget-network { justify-self: start; padding: 0; background: transparent; color: var(--bad); font-size: 13px; font-weight: 650; }
.switch-row { display: flex; align-items: center; justify-content: space-between; gap: 14px; min-height: 48px; color: var(--text); }
.switch-row strong { display: block; font-size: 14px; font-weight: 600; }
.switch-row small { display: block; margin-top: 2px; color: var(--muted); font-size: 12px; }
.switch { position: relative; width: 48px; height: 28px; flex: 0 0 auto; }
.switch input { position: absolute; inset: 0; width: 100%; height: 100%; margin: 0; opacity: 0; }
.switch span { position: absolute; inset: 0; border-radius: 999px; background: var(--border); }
.switch span::after { content: ""; position: absolute; top: 4px; left: 4px; width: 20px; height: 20px; border-radius: 50%; background: var(--card); box-shadow: 0 1px 4px rgba(0, 0, 0, 0.22); transition: transform 140ms ease; }
.switch input:checked + span { background: var(--primary); }
.switch input:checked + span::after { transform: translateX(20px); }
.form-actions { display: flex; gap: 8px; align-items: center; justify-content: flex-end; grid-column: 1 / -1; margin-top: 4px; }
#saveState { color: var(--muted); font-size: 13px; }

@media (max-width: 560px) {
  header { align-items: flex-start; flex-direction: column; }
  .actions,
  .toolbar { justify-content: flex-start; }
  .settings-overlay { align-items: flex-end; padding: 0; }
  .settings-dialog { width: 100%; max-height: 88vh; border-right: 0; border-bottom: 0; border-left: 0; }
}

  </style>
</head>
<body>
  <main>
    <header>
      <h1>Dev panel</h1>
      <div class="toolbar">
        <a href="/">Dashboard</a>
        <button id="refreshBtn" type="button">Refresh</button>
        <button id="themeToggle" type="button">Dark theme</button>
      </div>
    </header>

    <section class="grid wide">
      <div class="card"><div class="label">Simulation</div><div id="mode" class="value dev-value">--</div></div>
      <div class="card"><div class="label">Temperature</div><div id="temperature" class="value dev-value">--</div></div>
      <div class="card"><div class="label">Peltier</div><div id="peltier" class="value dev-value">--</div></div>
      <div class="card"><div class="label">Fan</div><div id="fan" class="value dev-value">--</div></div>
    </section>

    <section class="panel">
      <form id="devForm">
        <label class="check"><input id="enabledInput" name="enabled" type="checkbox"> Enable status simulation</label>
        <label class="label">Temperature, C<input id="temperatureInput" name="temperatureC" type="number" min="-127" max="125" step="0.1"></label>
        <label class="check"><input id="hasTemperatureInput" name="hasTemperature" type="checkbox"> Has temperature</label>
        <label class="check"><input id="sensorDisconnectedInput" name="sensorDisconnected" type="checkbox"> Sensor disconnected</label>
        <label class="check"><input id="peltierInput" name="peltierRunning" type="checkbox"> Peltier ON</label>
        <label class="check"><input id="fanInput" name="fanRunning" type="checkbox"> Fan ON</label>
        <label class="check"><input id="runOnInput" name="fanRunOnActive" type="checkbox"> Fan run-on active</label>
        <label class="label">Run-on remaining, ms<input id="remainingInput" name="fanRunOnRemainingMs" type="number" min="0" max="600000" step="1000"></label>
        <label class="label">Updates<input id="updatesInput" name="updateCount" type="number" min="0" max="999999" step="1"></label>
        <div class="toolbar">
          <button class="primary" type="submit">Apply</button>
          <button id="resetBtn" type="button">Disable simulation</button>
          <span id="saveState"></span>
        </div>
      </form>
    </section>
  </main>
  <script>
(function () {
  const storageKeys = {
    theme: 'cooling-dashboard.theme',
    legacyTheme: 'theme',
    devState: 'cooling-dashboard.devState'
  };
  const defaultDevState = {
    ok: true,
    enabled: false,
    temperatureC: 5.0,
    hasTemperature: true,
    sensorDisconnected: false,
    updateCount: 0,
    peltierRunning: false,
    fanRunning: false,
    fanRunOnActive: false,
    fanRunOnRemainingMs: 0
  };
  const setText = (id, text) => document.getElementById(id).textContent = text;
  const readStoredDevState = () => {
    try {
      return { ...defaultDevState, ...JSON.parse(localStorage.getItem(storageKeys.devState) || '{}') };
    } catch (error) {
      return { ...defaultDevState };
    }
  };
  const storeDevState = (data) => {
    localStorage.setItem(storageKeys.devState, JSON.stringify({ ...defaultDevState, ...data }));
  };
  const initTheme = () => {
    const themeToggle = document.getElementById('themeToggle');
    if (!themeToggle) return;
    const applyTheme = (theme) => {
      document.documentElement.dataset.theme = theme;
      themeToggle.textContent = theme === 'dark' ? 'Light theme' : 'Dark theme';
      localStorage.setItem(storageKeys.theme, theme);
      localStorage.setItem(storageKeys.legacyTheme, theme);
    };
    applyTheme(localStorage.getItem(storageKeys.theme) || localStorage.getItem(storageKeys.legacyTheme) || 'light');
    themeToggle.addEventListener('click', () => {
      applyTheme(document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark');
    });
  };
  window.CoolingWeb = {
    storageKeys,
    defaultDevState,
    initTheme,
    readStoredDevState,
    storeDevState,
    setText
  };
  document.addEventListener('DOMContentLoaded', initTheme);
}());

  </script>
  <script>
(function () {
  const { readStoredDevState, storeDevState, setText } = window.CoolingWeb;
  const ids = {
    enabled: 'enabledInput',
    temperatureC: 'temperatureInput',
    hasTemperature: 'hasTemperatureInput',
    sensorDisconnected: 'sensorDisconnectedInput',
    peltierRunning: 'peltierInput',
    fanRunning: 'fanInput',
    fanRunOnActive: 'runOnInput',
    fanRunOnRemainingMs: 'remainingInput',
    updateCount: 'updatesInput'
  };
  const setChecked = (id, value) => document.getElementById(id).checked = Boolean(value);
  const setValue = (id, value) => document.getElementById(id).value = value;

  document.addEventListener('DOMContentLoaded', () => {
    const saveState = document.getElementById('saveState');
    const setSaveState = (text, isError = false) => {
      saveState.textContent = text;
      saveState.className = isError ? 'danger' : '';
    };
    const formData = () => {
      const body = new URLSearchParams();
      body.set('enabled', document.getElementById(ids.enabled).checked ? '1' : '0');
      body.set('temperatureC', document.getElementById(ids.temperatureC).value || '0');
      body.set('hasTemperature', document.getElementById(ids.hasTemperature).checked ? '1' : '0');
      body.set('sensorDisconnected', document.getElementById(ids.sensorDisconnected).checked ? '1' : '0');
      body.set('peltierRunning', document.getElementById(ids.peltierRunning).checked ? '1' : '0');
      body.set('fanRunning', document.getElementById(ids.fanRunning).checked ? '1' : '0');
      body.set('fanRunOnActive', document.getElementById(ids.fanRunOnActive).checked ? '1' : '0');
      body.set('fanRunOnRemainingMs', document.getElementById(ids.fanRunOnRemainingMs).value || '0');
      body.set('updateCount', document.getElementById(ids.updateCount).value || '0');
      return body;
    };
    const applyState = (data) => {
      storeDevState(data);
      setChecked(ids.enabled, data.enabled);
      setValue(ids.temperatureC, Number(data.temperatureC).toFixed(1));
      setChecked(ids.hasTemperature, data.hasTemperature);
      setChecked(ids.sensorDisconnected, data.sensorDisconnected);
      setChecked(ids.peltierRunning, data.peltierRunning);
      setChecked(ids.fanRunning, data.fanRunning);
      setChecked(ids.fanRunOnActive, data.fanRunOnActive);
      setValue(ids.fanRunOnRemainingMs, data.fanRunOnRemainingMs);
      setValue(ids.updateCount, data.updateCount);
      setText('mode', data.enabled ? 'ON' : 'OFF');
      setText('temperature', data.hasTemperature ? Number(data.temperatureC).toFixed(1) + ' C' : '--');
      setText('peltier', data.peltierRunning ? 'ON' : 'OFF');
      setText('fan', data.fanRunning ? 'ON' : 'OFF');
    };
    async function loadDev() {
      try {
        const res = await fetch('/api/dev', { cache: 'no-store' });
        if (!res.ok) throw new Error('dev state unavailable');
        applyState(await res.json());
      } catch (error) {
        applyState(readStoredDevState());
        setSaveState('Local state');
      }
    }
    async function saveDev(body) {
      setSaveState('Saving...');
      const localState = {
        ok: true,
        enabled: body.get('enabled') === '1',
        temperatureC: Number(body.get('temperatureC')),
        hasTemperature: body.get('hasTemperature') === '1',
        sensorDisconnected: body.get('sensorDisconnected') === '1',
        updateCount: Number(body.get('updateCount')),
        peltierRunning: body.get('peltierRunning') === '1',
        fanRunning: body.get('fanRunning') === '1',
        fanRunOnActive: body.get('fanRunOnActive') === '1',
        fanRunOnRemainingMs: Number(body.get('fanRunOnRemainingMs'))
      };
      try {
        const res = await fetch('/api/dev', {
          method: 'POST',
          headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
          body
        });
        if (!res.ok) throw new Error('save failed');
        applyState(await res.json());
        setSaveState('Applied');
      } catch (error) {
        applyState(localState);
        setSaveState('Applied locally');
      }
    }
    document.getElementById('devForm').addEventListener('submit', async (event) => {
      event.preventDefault();
      try {
        await saveDev(formData());
      } catch (error) {
        setSaveState('Apply failed', true);
      }
    });
    document.getElementById('resetBtn').addEventListener('click', async () => {
      const body = formData();
      body.set('enabled', '0');
      await saveDev(body);
    });
    document.getElementById('refreshBtn').addEventListener('click', loadDev);
    loadDev();
  });
}());

  </script>
</body>
</html>

)dev_html";
inline const char *webPageForPath(const String &path)
{
  if (path == "/" || path == "/dashboard.html") { return kIndexHtml; }
  if (path == "/dev" || path == "/dev.html") { return kDevHtml; }
  return nullptr;
}
