#pragma once

#include <Arduino.h>

// Generated by tools/embed_dashboard.py from web/dashboard.html.
const char kIndexHtml[] PROGMEM = R"dashboard_html(
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Cooling Controller</title>
  <style>
:root {
  color-scheme: light;
  font-family: system-ui, sans-serif;
  --bg: #f5f7f8;
  --text: #172126;
  --muted: #68787f;
  --card: #ffffff;
  --border: #dce4e7;
  --ok: #11773d;
  --bad: #bf3030;
  --demo-bg: #fff2bd;
  --demo-text: #6b4b00;
  --button: #e7eef1;
  --button-text: #172126;
  --primary: #176b4d;
  --input: #ffffff;
  --overlay: rgba(12, 18, 20, 0.42);
  --shadow: 0 18px 60px rgba(21, 32, 36, 0.18);
}

[data-theme="dark"] {
  color-scheme: dark;
  --bg: #101417;
  --text: #eef4f2;
  --muted: #95a3a0;
  --card: #182024;
  --border: #2b3638;
  --ok: #65d38a;
  --bad: #ff7474;
  --demo-bg: #4a3610;
  --demo-text: #ffd979;
  --button: #283236;
  --button-text: #eef4f2;
  --input: #11181b;
  --overlay: rgba(0, 0, 0, 0.58);
  --shadow: 0 18px 60px rgba(0, 0, 0, 0.36);
}

body { margin: 0; background: var(--bg); color: var(--text); }
main { max-width: 860px; margin: 0 auto; padding: 22px; }
.narrow { max-width: 760px; }
header { display: flex; align-items: center; justify-content: space-between; gap: 12px; margin-bottom: 18px; }
h1 { margin: 0; font-size: 26px; font-weight: 700; }
h2 { margin: 0; font-size: 18px; }
button,
a.button,
.toolbar a {
  border: 0;
  border-radius: 8px;
  padding: 9px 12px;
  background: var(--button);
  color: var(--button-text);
  font: inherit;
  font-size: 14px;
  text-decoration: none;
}
button.primary { background: var(--primary); color: #ffffff; }
.subtle { opacity: 0.72; }
.danger { color: var(--bad); }
.actions,
.toolbar { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; justify-content: flex-end; }
.badge { border-radius: 999px; padding: 6px 9px; background: var(--demo-bg); color: var(--demo-text); font-size: 12px; font-weight: 700; text-transform: uppercase; }
.hidden { display: none; }
.grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(170px, 1fr)); gap: 10px; }
.grid.wide { grid-template-columns: repeat(auto-fit, minmax(190px, 1fr)); }
.card { border: 1px solid var(--border); border-radius: 8px; padding: 14px; background: var(--card); }
.label { color: var(--muted); font-size: 13px; }
.value { margin-top: 8px; font-size: 28px; font-weight: 700; }
.small { font-size: 18px; }
.dev-value { font-size: 22px; }
.ok { color: var(--ok); }
.bad { color: var(--bad); }
.panel { border-top: 1px solid var(--border); padding-top: 14px; margin-top: 14px; }
form { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 10px; align-items: end; }
input,
select { box-sizing: border-box; width: 100%; margin-top: 6px; border: 1px solid var(--border); border-radius: 8px; padding: 9px 10px; background: var(--input); color: var(--text); font: inherit; }
.check { display: flex; gap: 8px; align-items: center; min-height: 38px; }
.check input { width: auto; margin: 0; }
.settings-overlay { position: fixed; inset: 0; display: none; align-items: center; justify-content: center; padding: 18px; background: var(--overlay); z-index: 10; }
.settings-overlay.open { display: flex; }
.settings-dialog { width: min(620px, 100%); max-height: calc(100vh - 36px); overflow: auto; border: 1px solid var(--border); border-radius: 8px; background: var(--card); box-shadow: var(--shadow); }
.settings-head { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 14px 16px; border-bottom: 1px solid var(--border); }
.settings-section { grid-column: 1 / -1; display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 10px; padding-top: 12px; border-top: 1px solid var(--border); }
.settings-section:first-child { padding-top: 0; border-top: 0; }
.section-title { grid-column: 1 / -1; margin: 0; color: var(--muted); font-size: 13px; font-weight: 700; text-transform: uppercase; }
.network-status { grid-column: 1 / -1; display: grid; grid-template-columns: repeat(auto-fit, minmax(170px, 1fr)); gap: 8px; }
.status-line { min-width: 0; border: 1px solid var(--border); border-radius: 8px; padding: 9px 10px; background: var(--bg); }
.status-line strong { display: block; color: var(--muted); font-size: 12px; font-weight: 700; }
.status-line span { display: block; margin-top: 4px; overflow-wrap: anywhere; font-size: 14px; }
.form-actions { display: flex; gap: 8px; align-items: center; justify-content: flex-end; grid-column: 1 / -1; margin-top: 4px; }
#saveState { color: var(--muted); font-size: 13px; }

@media (max-width: 560px) {
  header { align-items: flex-start; flex-direction: column; }
  .actions,
  .toolbar { justify-content: flex-start; }
  .settings-overlay { align-items: flex-end; padding: 0; }
  .settings-dialog { width: 100%; max-height: 88vh; border-right: 0; border-bottom: 0; border-left: 0; }
}

  </style>
</head>
<body>
  <main class="narrow">
    <header>
      <h1>Cooling Controller</h1>
      <div class="actions">
        <span id="demoBadge" class="badge hidden">Demo scene</span>
        <span id="devBadge" class="badge hidden">Dev mode</span>
        <button id="settingsOpen" type="button">Settings</button>
        <a class="button subtle" href="/dev">Dev</a>
        <button id="themeToggle" type="button">Dark theme</button>
      </div>
    </header>
    <section class="grid">
      <div class="card"><div class="label">Temperature</div><div id="temperature" class="value">--</div></div>
      <div class="card"><div class="label">Sensor</div><div id="sensor" class="value small">--</div></div>
      <div class="card"><div class="label">Peltier</div><div id="peltier" class="value small">--</div></div>
      <div class="card"><div class="label">Fan</div><div id="fan" class="value small">--</div></div>
      <div class="card"><div class="label">Fan run-on</div><div id="runon" class="value small">--</div></div>
      <div class="card"><div class="label">Updates</div><div id="count" class="value small">--</div></div>
      <div class="card"><div class="label">Target</div><div id="target" class="value small">--</div></div>
      <div class="card"><div class="label">Uptime</div><div id="uptime" class="value small">--</div></div>
      <div class="card"><div class="label">WiFi network</div><div id="wifi" class="value small">--</div></div>
    </section>
  </main>
  <div id="settingsOverlay" class="settings-overlay" role="dialog" aria-modal="true" aria-labelledby="settingsTitle">
    <section class="settings-dialog">
      <div class="settings-head">
        <h2 id="settingsTitle">Control settings</h2>
        <button id="settingsClose" type="button">Close</button>
      </div>
      <form id="settingsForm">
        <section class="settings-section">
          <h3 class="section-title">Cooling</h3>
          <label class="label">Target, C<input id="targetInput" name="targetC" type="number" min="-20" max="40" step="0.1" required></label>
          <label class="label">Hysteresis, C<input id="hysteresisInput" name="hysteresisC" type="number" min="0.1" max="10" step="0.1" required></label>
          <label class="label">Measurement, ms<input id="measurementInput" name="measurementIntervalMs" type="number" min="250" max="60000" step="50" required></label>
          <label class="label">Fan run-on, ms<input id="fanRunOnInput" name="fanRunOnMs" type="number" min="0" max="600000" step="1000" required></label>
        </section>
        <section class="settings-section">
          <h3 class="section-title">Network</h3>
          <div class="network-status">
            <div class="status-line"><strong>Own network</strong><span id="apStatus">--</span></div>
            <div class="status-line"><strong>Own page</strong><span id="apPageStatus">--</span></div>
            <div class="status-line"><strong>Connected network</strong><span id="stationStatus">--</span></div>
            <div class="status-line"><strong>Connected page</strong><span id="stationPageStatus">--</span></div>
            <div class="status-line"><strong>Current page</strong><span id="currentPageStatus">--</span></div>
          </div>
          <label class="label">Network SSID<input id="stationSsidInput" name="stationSsid" type="text" maxlength="32" autocomplete="off"></label>
          <label class="label">Network password<input id="stationPasswordInput" name="stationPassword" type="password" maxlength="64" autocomplete="new-password" placeholder="Leave blank to keep saved"></label>
          <label class="check"><input id="clearStationPasswordInput" name="clearStationPassword" type="checkbox" value="1"> Clear saved password</label>
        </section>
        <div class="form-actions">
          <span id="saveState"></span>
          <button class="primary" type="submit">Save</button>
        </div>
      </form>
    </section>
  </div>
  <script>
(function () {
  const storageKeys = {
    theme: 'cooling-dashboard.theme',
    legacyTheme: 'theme',
    devState: 'cooling-dashboard.devState'
  };
  const defaultDevState = {
    ok: true,
    enabled: false,
    temperatureC: 5.0,
    hasTemperature: true,
    sensorDisconnected: false,
    updateCount: 0,
    peltierRunning: false,
    fanRunning: false,
    fanRunOnActive: false,
    fanRunOnRemainingMs: 0
  };
  const setText = (id, text) => document.getElementById(id).textContent = text;
  const readStoredDevState = () => {
    try {
      return { ...defaultDevState, ...JSON.parse(localStorage.getItem(storageKeys.devState) || '{}') };
    } catch (error) {
      return { ...defaultDevState };
    }
  };
  const storeDevState = (data) => {
    localStorage.setItem(storageKeys.devState, JSON.stringify({ ...defaultDevState, ...data }));
  };
  const initTheme = () => {
    const themeToggle = document.getElementById('themeToggle');
    if (!themeToggle) return;
    const applyTheme = (theme) => {
      document.documentElement.dataset.theme = theme;
      themeToggle.textContent = theme === 'dark' ? 'Light theme' : 'Dark theme';
      localStorage.setItem(storageKeys.theme, theme);
      localStorage.setItem(storageKeys.legacyTheme, theme);
    };
    applyTheme(localStorage.getItem(storageKeys.theme) || localStorage.getItem(storageKeys.legacyTheme) || 'light');
    themeToggle.addEventListener('click', () => {
      applyTheme(document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark');
    });
  };
  window.CoolingWeb = {
    storageKeys,
    defaultDevState,
    initTheme,
    readStoredDevState,
    storeDevState,
    setText
  };
  document.addEventListener('DOMContentLoaded', initTheme);
}());

  </script>
  <script>
(function () {
  const { readStoredDevState, setText } = window.CoolingWeb;
  const startedAt = Date.now();
  const setState = (id, on) => {
    const el = document.getElementById(id);
    el.textContent = on ? 'ON' : 'OFF';
    el.className = 'value small ' + (on ? 'ok' : '');
  };
  const mockStatus = () => {
    const elapsedMs = Date.now() - startedAt;
    const peltierRunning = Math.floor(elapsedMs / 7000) % 2 === 0;
    return {
      temperatureC: 5.4 + Math.sin(elapsedMs / 3500) * 0.8,
      hasTemperature: true,
      sensorDisconnected: false,
      updateCount: Math.floor(elapsedMs / 1000),
      peltierRunning,
      fanRunning: peltierRunning || Math.floor(elapsedMs / 3000) % 5 === 0,
      fanRunOnActive: !peltierRunning && Math.floor(elapsedMs / 3000) % 5 === 0,
      fanRunOnRemainingMs: 12000 - (elapsedMs % 12000),
      targetC: 5.0,
      hysteresisC: 0.1,
      measurementIntervalMs: 500,
      fanRunOnMs: 30000,
      uptimeMs: elapsedMs,
      accessPointSsid: 'CoolingController',
      accessPointIp: '',
      stationSsid: '',
      stationPasswordSet: false,
      stationConnected: false,
      stationStatus: 'disabled',
      stationIp: '',
      stationRssi: 0,
      devMode: false,
      demo: true
    };
  };
  const mockFromDevState = (devState, elapsedMs) => ({
    temperatureC: Number(devState.temperatureC) || 0,
    hasTemperature: Boolean(devState.hasTemperature),
    sensorDisconnected: Boolean(devState.sensorDisconnected),
    updateCount: Number(devState.updateCount) || 0,
    peltierRunning: Boolean(devState.peltierRunning),
    fanRunning: Boolean(devState.fanRunning),
    fanRunOnActive: Boolean(devState.fanRunOnActive),
    fanRunOnRemainingMs: Number(devState.fanRunOnRemainingMs) || 0,
    targetC: 5.0,
    hysteresisC: 0.1,
    measurementIntervalMs: 500,
    fanRunOnMs: 30000,
    uptimeMs: elapsedMs,
    accessPointSsid: 'CoolingController',
    accessPointIp: '',
    stationSsid: '',
    stationPasswordSet: false,
    stationConnected: false,
    stationStatus: 'disabled',
    stationIp: '',
    stationRssi: 0,
    devMode: true,
    demo: true
  });
  const pageUrl = (ip) => ip ? 'http://' + ip + '/' : '--';

  document.addEventListener('DOMContentLoaded', () => {
    const demoBadge = document.getElementById('demoBadge');
    const devBadge = document.getElementById('devBadge');
    const settingsForm = document.getElementById('settingsForm');
    const settingsOverlay = document.getElementById('settingsOverlay');
    const settingsOpen = document.getElementById('settingsOpen');
    const settingsClose = document.getElementById('settingsClose');
    const saveState = document.getElementById('saveState');
    let settingsDirty = false;
    const applySettingsToForm = (data) => {
      if (settingsDirty) return;
      document.getElementById('targetInput').value = Number(data.targetC).toFixed(1);
      document.getElementById('hysteresisInput').value = Number(data.hysteresisC).toFixed(1);
      document.getElementById('measurementInput').value = data.measurementIntervalMs;
      document.getElementById('fanRunOnInput').value = data.fanRunOnMs;
      document.getElementById('stationSsidInput').value = data.stationSsid || '';
      document.getElementById('stationPasswordInput').value = '';
      document.getElementById('stationPasswordInput').placeholder = data.stationPasswordSet ? 'Saved; leave blank to keep' : 'Leave blank for open network';
      document.getElementById('clearStationPasswordInput').checked = false;
    };
    const renderNetworkStatus = (data) => {
      setText('apStatus', data.accessPointSsid || '--');
      setText('apPageStatus', pageUrl(data.accessPointIp));
      setText('stationStatus', data.stationSsid ? (data.stationConnected ? data.stationSsid + ' / ' + data.stationRssi + ' dBm' : data.stationSsid + ' / ' + (data.stationStatus || 'disconnected')) : 'Disabled');
      setText('stationPageStatus', data.stationConnected ? pageUrl(data.stationIp) : '--');
      setText('currentPageStatus', window.location.origin || '--');
    };
    const openSettings = () => {
      settingsOverlay.classList.add('open');
      settingsOpen.setAttribute('aria-expanded', 'true');
      document.getElementById('targetInput').focus();
    };
    const closeSettings = () => {
      settingsOverlay.classList.remove('open');
      settingsOpen.setAttribute('aria-expanded', 'false');
      settingsOpen.focus();
    };
    settingsOpen.setAttribute('aria-expanded', 'false');
    settingsOpen.addEventListener('click', openSettings);
    settingsClose.addEventListener('click', closeSettings);
    settingsOverlay.addEventListener('click', (event) => {
      if (event.target === settingsOverlay) closeSettings();
    });
    document.addEventListener('keydown', (event) => {
      if (event.key === 'Escape' && settingsOverlay.classList.contains('open')) closeSettings();
    });
    async function loadStatus() {
      try {
        const res = await fetch('/api/status', { cache: 'no-store' });
        if (!res.ok) throw new Error('status unavailable');
        const data = await res.json();
        data.demo = false;
        return data;
      } catch (error) {
        const devState = readStoredDevState();
        return devState.enabled ? mockFromDevState(devState, Date.now() - startedAt) : mockStatus();
      }
    }
    async function refresh() {
      const data = await loadStatus();
      demoBadge.classList.toggle('hidden', !data.demo);
      devBadge.classList.toggle('hidden', !data.devMode);
      setText('temperature', data.hasTemperature ? data.temperatureC.toFixed(1) + ' C' : '--');
      const sensor = document.getElementById('sensor');
      sensor.textContent = data.sensorDisconnected ? 'ERROR' : 'OK';
      sensor.className = 'value small ' + (data.sensorDisconnected ? 'bad' : 'ok');
      setState('peltier', data.peltierRunning);
      setState('fan', data.fanRunning);
      setText('runon', data.fanRunOnActive ? Math.ceil(data.fanRunOnRemainingMs / 1000) + ' s' : 'OFF');
      setText('count', data.updateCount);
      setText('target', data.targetC.toFixed(1) + ' C / hys ' + data.hysteresisC.toFixed(1));
      setText('uptime', Math.floor(data.uptimeMs / 1000) + ' s');
      setText('wifi', data.stationSsid ? (data.stationConnected ? data.stationIp : (data.stationStatus || 'Disconnected')) : 'Disabled');
      renderNetworkStatus(data);
      applySettingsToForm(data);
    }
    settingsForm.addEventListener('input', () => {
      settingsDirty = true;
      saveState.textContent = '';
    });
    settingsForm.addEventListener('submit', async (event) => {
      event.preventDefault();
      saveState.textContent = 'Saving...';
      try {
        const body = new URLSearchParams(new FormData(settingsForm));
        const res = await fetch('/api/settings', {
          method: 'POST',
          headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
          body
        });
        if (!res.ok) throw new Error('save failed');
        const data = await res.json();
        settingsDirty = false;
        applySettingsToForm(data);
        saveState.textContent = 'Saved';
        await refresh();
      } catch (error) {
        saveState.textContent = 'Save failed';
      }
    });
    refresh();
    setInterval(refresh, 1000);
  });
}());

  </script>
</body>
</html>

)dashboard_html";

// Generated by tools/embed_dashboard.py from web/dev.html.
const char kDevHtml[] PROGMEM = R"dev_html(
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Cooling Controller Dev</title>
  <style>
:root {
  color-scheme: light;
  font-family: system-ui, sans-serif;
  --bg: #f5f7f8;
  --text: #172126;
  --muted: #68787f;
  --card: #ffffff;
  --border: #dce4e7;
  --ok: #11773d;
  --bad: #bf3030;
  --demo-bg: #fff2bd;
  --demo-text: #6b4b00;
  --button: #e7eef1;
  --button-text: #172126;
  --primary: #176b4d;
  --input: #ffffff;
  --overlay: rgba(12, 18, 20, 0.42);
  --shadow: 0 18px 60px rgba(21, 32, 36, 0.18);
}

[data-theme="dark"] {
  color-scheme: dark;
  --bg: #101417;
  --text: #eef4f2;
  --muted: #95a3a0;
  --card: #182024;
  --border: #2b3638;
  --ok: #65d38a;
  --bad: #ff7474;
  --demo-bg: #4a3610;
  --demo-text: #ffd979;
  --button: #283236;
  --button-text: #eef4f2;
  --input: #11181b;
  --overlay: rgba(0, 0, 0, 0.58);
  --shadow: 0 18px 60px rgba(0, 0, 0, 0.36);
}

body { margin: 0; background: var(--bg); color: var(--text); }
main { max-width: 860px; margin: 0 auto; padding: 22px; }
.narrow { max-width: 760px; }
header { display: flex; align-items: center; justify-content: space-between; gap: 12px; margin-bottom: 18px; }
h1 { margin: 0; font-size: 26px; font-weight: 700; }
h2 { margin: 0; font-size: 18px; }
button,
a.button,
.toolbar a {
  border: 0;
  border-radius: 8px;
  padding: 9px 12px;
  background: var(--button);
  color: var(--button-text);
  font: inherit;
  font-size: 14px;
  text-decoration: none;
}
button.primary { background: var(--primary); color: #ffffff; }
.subtle { opacity: 0.72; }
.danger { color: var(--bad); }
.actions,
.toolbar { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; justify-content: flex-end; }
.badge { border-radius: 999px; padding: 6px 9px; background: var(--demo-bg); color: var(--demo-text); font-size: 12px; font-weight: 700; text-transform: uppercase; }
.hidden { display: none; }
.grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(170px, 1fr)); gap: 10px; }
.grid.wide { grid-template-columns: repeat(auto-fit, minmax(190px, 1fr)); }
.card { border: 1px solid var(--border); border-radius: 8px; padding: 14px; background: var(--card); }
.label { color: var(--muted); font-size: 13px; }
.value { margin-top: 8px; font-size: 28px; font-weight: 700; }
.small { font-size: 18px; }
.dev-value { font-size: 22px; }
.ok { color: var(--ok); }
.bad { color: var(--bad); }
.panel { border-top: 1px solid var(--border); padding-top: 14px; margin-top: 14px; }
form { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 10px; align-items: end; }
input,
select { box-sizing: border-box; width: 100%; margin-top: 6px; border: 1px solid var(--border); border-radius: 8px; padding: 9px 10px; background: var(--input); color: var(--text); font: inherit; }
.check { display: flex; gap: 8px; align-items: center; min-height: 38px; }
.check input { width: auto; margin: 0; }
.settings-overlay { position: fixed; inset: 0; display: none; align-items: center; justify-content: center; padding: 18px; background: var(--overlay); z-index: 10; }
.settings-overlay.open { display: flex; }
.settings-dialog { width: min(620px, 100%); max-height: calc(100vh - 36px); overflow: auto; border: 1px solid var(--border); border-radius: 8px; background: var(--card); box-shadow: var(--shadow); }
.settings-head { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 14px 16px; border-bottom: 1px solid var(--border); }
.settings-section { grid-column: 1 / -1; display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 10px; padding-top: 12px; border-top: 1px solid var(--border); }
.settings-section:first-child { padding-top: 0; border-top: 0; }
.section-title { grid-column: 1 / -1; margin: 0; color: var(--muted); font-size: 13px; font-weight: 700; text-transform: uppercase; }
.network-status { grid-column: 1 / -1; display: grid; grid-template-columns: repeat(auto-fit, minmax(170px, 1fr)); gap: 8px; }
.status-line { min-width: 0; border: 1px solid var(--border); border-radius: 8px; padding: 9px 10px; background: var(--bg); }
.status-line strong { display: block; color: var(--muted); font-size: 12px; font-weight: 700; }
.status-line span { display: block; margin-top: 4px; overflow-wrap: anywhere; font-size: 14px; }
.form-actions { display: flex; gap: 8px; align-items: center; justify-content: flex-end; grid-column: 1 / -1; margin-top: 4px; }
#saveState { color: var(--muted); font-size: 13px; }

@media (max-width: 560px) {
  header { align-items: flex-start; flex-direction: column; }
  .actions,
  .toolbar { justify-content: flex-start; }
  .settings-overlay { align-items: flex-end; padding: 0; }
  .settings-dialog { width: 100%; max-height: 88vh; border-right: 0; border-bottom: 0; border-left: 0; }
}

  </style>
</head>
<body>
  <main>
    <header>
      <h1>Dev panel</h1>
      <div class="toolbar">
        <a href="/">Dashboard</a>
        <button id="refreshBtn" type="button">Refresh</button>
        <button id="themeToggle" type="button">Dark theme</button>
      </div>
    </header>

    <section class="grid wide">
      <div class="card"><div class="label">Simulation</div><div id="mode" class="value dev-value">--</div></div>
      <div class="card"><div class="label">Temperature</div><div id="temperature" class="value dev-value">--</div></div>
      <div class="card"><div class="label">Peltier</div><div id="peltier" class="value dev-value">--</div></div>
      <div class="card"><div class="label">Fan</div><div id="fan" class="value dev-value">--</div></div>
    </section>

    <section class="panel">
      <form id="devForm">
        <label class="check"><input id="enabledInput" name="enabled" type="checkbox"> Enable status simulation</label>
        <label class="label">Temperature, C<input id="temperatureInput" name="temperatureC" type="number" min="-127" max="125" step="0.1"></label>
        <label class="check"><input id="hasTemperatureInput" name="hasTemperature" type="checkbox"> Has temperature</label>
        <label class="check"><input id="sensorDisconnectedInput" name="sensorDisconnected" type="checkbox"> Sensor disconnected</label>
        <label class="check"><input id="peltierInput" name="peltierRunning" type="checkbox"> Peltier ON</label>
        <label class="check"><input id="fanInput" name="fanRunning" type="checkbox"> Fan ON</label>
        <label class="check"><input id="runOnInput" name="fanRunOnActive" type="checkbox"> Fan run-on active</label>
        <label class="label">Run-on remaining, ms<input id="remainingInput" name="fanRunOnRemainingMs" type="number" min="0" max="600000" step="1000"></label>
        <label class="label">Updates<input id="updatesInput" name="updateCount" type="number" min="0" max="999999" step="1"></label>
        <div class="toolbar">
          <button class="primary" type="submit">Apply</button>
          <button id="resetBtn" type="button">Disable simulation</button>
          <span id="saveState"></span>
        </div>
      </form>
    </section>
  </main>
  <script>
(function () {
  const storageKeys = {
    theme: 'cooling-dashboard.theme',
    legacyTheme: 'theme',
    devState: 'cooling-dashboard.devState'
  };
  const defaultDevState = {
    ok: true,
    enabled: false,
    temperatureC: 5.0,
    hasTemperature: true,
    sensorDisconnected: false,
    updateCount: 0,
    peltierRunning: false,
    fanRunning: false,
    fanRunOnActive: false,
    fanRunOnRemainingMs: 0
  };
  const setText = (id, text) => document.getElementById(id).textContent = text;
  const readStoredDevState = () => {
    try {
      return { ...defaultDevState, ...JSON.parse(localStorage.getItem(storageKeys.devState) || '{}') };
    } catch (error) {
      return { ...defaultDevState };
    }
  };
  const storeDevState = (data) => {
    localStorage.setItem(storageKeys.devState, JSON.stringify({ ...defaultDevState, ...data }));
  };
  const initTheme = () => {
    const themeToggle = document.getElementById('themeToggle');
    if (!themeToggle) return;
    const applyTheme = (theme) => {
      document.documentElement.dataset.theme = theme;
      themeToggle.textContent = theme === 'dark' ? 'Light theme' : 'Dark theme';
      localStorage.setItem(storageKeys.theme, theme);
      localStorage.setItem(storageKeys.legacyTheme, theme);
    };
    applyTheme(localStorage.getItem(storageKeys.theme) || localStorage.getItem(storageKeys.legacyTheme) || 'light');
    themeToggle.addEventListener('click', () => {
      applyTheme(document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark');
    });
  };
  window.CoolingWeb = {
    storageKeys,
    defaultDevState,
    initTheme,
    readStoredDevState,
    storeDevState,
    setText
  };
  document.addEventListener('DOMContentLoaded', initTheme);
}());

  </script>
  <script>
(function () {
  const { readStoredDevState, storeDevState, setText } = window.CoolingWeb;
  const ids = {
    enabled: 'enabledInput',
    temperatureC: 'temperatureInput',
    hasTemperature: 'hasTemperatureInput',
    sensorDisconnected: 'sensorDisconnectedInput',
    peltierRunning: 'peltierInput',
    fanRunning: 'fanInput',
    fanRunOnActive: 'runOnInput',
    fanRunOnRemainingMs: 'remainingInput',
    updateCount: 'updatesInput'
  };
  const setChecked = (id, value) => document.getElementById(id).checked = Boolean(value);
  const setValue = (id, value) => document.getElementById(id).value = value;

  document.addEventListener('DOMContentLoaded', () => {
    const saveState = document.getElementById('saveState');
    const setSaveState = (text, isError = false) => {
      saveState.textContent = text;
      saveState.className = isError ? 'danger' : '';
    };
    const formData = () => {
      const body = new URLSearchParams();
      body.set('enabled', document.getElementById(ids.enabled).checked ? '1' : '0');
      body.set('temperatureC', document.getElementById(ids.temperatureC).value || '0');
      body.set('hasTemperature', document.getElementById(ids.hasTemperature).checked ? '1' : '0');
      body.set('sensorDisconnected', document.getElementById(ids.sensorDisconnected).checked ? '1' : '0');
      body.set('peltierRunning', document.getElementById(ids.peltierRunning).checked ? '1' : '0');
      body.set('fanRunning', document.getElementById(ids.fanRunning).checked ? '1' : '0');
      body.set('fanRunOnActive', document.getElementById(ids.fanRunOnActive).checked ? '1' : '0');
      body.set('fanRunOnRemainingMs', document.getElementById(ids.fanRunOnRemainingMs).value || '0');
      body.set('updateCount', document.getElementById(ids.updateCount).value || '0');
      return body;
    };
    const applyState = (data) => {
      storeDevState(data);
      setChecked(ids.enabled, data.enabled);
      setValue(ids.temperatureC, Number(data.temperatureC).toFixed(1));
      setChecked(ids.hasTemperature, data.hasTemperature);
      setChecked(ids.sensorDisconnected, data.sensorDisconnected);
      setChecked(ids.peltierRunning, data.peltierRunning);
      setChecked(ids.fanRunning, data.fanRunning);
      setChecked(ids.fanRunOnActive, data.fanRunOnActive);
      setValue(ids.fanRunOnRemainingMs, data.fanRunOnRemainingMs);
      setValue(ids.updateCount, data.updateCount);
      setText('mode', data.enabled ? 'ON' : 'OFF');
      setText('temperature', data.hasTemperature ? Number(data.temperatureC).toFixed(1) + ' C' : '--');
      setText('peltier', data.peltierRunning ? 'ON' : 'OFF');
      setText('fan', data.fanRunning ? 'ON' : 'OFF');
    };
    async function loadDev() {
      try {
        const res = await fetch('/api/dev', { cache: 'no-store' });
        if (!res.ok) throw new Error('dev state unavailable');
        applyState(await res.json());
      } catch (error) {
        applyState(readStoredDevState());
        setSaveState('Local state');
      }
    }
    async function saveDev(body) {
      setSaveState('Saving...');
      const localState = {
        ok: true,
        enabled: body.get('enabled') === '1',
        temperatureC: Number(body.get('temperatureC')),
        hasTemperature: body.get('hasTemperature') === '1',
        sensorDisconnected: body.get('sensorDisconnected') === '1',
        updateCount: Number(body.get('updateCount')),
        peltierRunning: body.get('peltierRunning') === '1',
        fanRunning: body.get('fanRunning') === '1',
        fanRunOnActive: body.get('fanRunOnActive') === '1',
        fanRunOnRemainingMs: Number(body.get('fanRunOnRemainingMs'))
      };
      try {
        const res = await fetch('/api/dev', {
          method: 'POST',
          headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
          body
        });
        if (!res.ok) throw new Error('save failed');
        applyState(await res.json());
        setSaveState('Applied');
      } catch (error) {
        applyState(localState);
        setSaveState('Applied locally');
      }
    }
    document.getElementById('devForm').addEventListener('submit', async (event) => {
      event.preventDefault();
      try {
        await saveDev(formData());
      } catch (error) {
        setSaveState('Apply failed', true);
      }
    });
    document.getElementById('resetBtn').addEventListener('click', async () => {
      const body = formData();
      body.set('enabled', '0');
      await saveDev(body);
    });
    document.getElementById('refreshBtn').addEventListener('click', loadDev);
    loadDev();
  });
}());

  </script>
</body>
</html>

)dev_html";
inline const char *webPageForPath(const String &path)
{
  if (path == "/" || path == "/dashboard.html") { return kIndexHtml; }
  if (path == "/dev" || path == "/dev.html") { return kDevHtml; }
  return nullptr;
}
