from html.parser import HTMLParser
from pathlib import Path
import re

Import("env")

PROJECT_DIR = Path(env.subst("$PROJECT_DIR"))
WEB_DIR = PROJECT_DIR / "web"
TARGET = PROJECT_DIR / "include" / "web" / "WebDashboardPage.h"


class AssetCollector(HTMLParser):
    def __init__(self):
        super().__init__()
        self.assets = []

    def handle_starttag(self, tag, attrs):
        attr_map = dict(attrs)
        if tag == "link" and attr_map.get("rel") == "stylesheet":
            self.assets.append(attr_map.get("href", ""))
        if tag == "script" and "src" in attr_map:
            self.assets.append(attr_map.get("src", ""))


def page_files():
    return sorted(
        WEB_DIR.glob("*.html"),
        key=lambda path: (path.name != "dashboard.html", path.name),
    )


def c_identifier(text):
    return re.sub(r"[^A-Za-z0-9_]+", "_", text).strip("_")


def symbol_name(source_path):
    if source_path.name == "dashboard.html":
        return "kIndexHtml"
    name = c_identifier(source_path.stem)
    return "k" + name[:1].upper() + name[1:] + "Html"


def delimiter_name(source_path):
    return c_identifier(source_path.stem) + "_html"


def routes_for(source_path):
    if source_path.name == "dashboard.html":
        return ["/", "/dashboard.html"]
    return ["/" + source_path.stem, "/" + source_path.name]


def local_asset_path(url):
    if not url.startswith("/"):
        return None
    path = (WEB_DIR / url.lstrip("/")).resolve()
    try:
        path.relative_to(WEB_DIR)
    except ValueError:
        return None
    return path if path.is_file() else None


def inline_assets(html):
    collector = AssetCollector()
    collector.feed(html)
    for url in collector.assets:
        asset_path = local_asset_path(url)
        if asset_path is None:
            continue
        content = asset_path.read_text(encoding="utf-8")
        if asset_path.suffix == ".css":
            html = html.replace(
                f'<link rel="stylesheet" href="{url}">',
                f"<style>\n{content}\n  </style>",
            )
        elif asset_path.suffix == ".js":
            html = html.replace(
                f'<script src="{url}"></script>',
                f"<script>\n{content}\n  </script>",
            )
    return html


def build_page(source_path):
    delimiter = delimiter_name(source_path)
    html = inline_assets(source_path.read_text(encoding="utf-8"))
    if f"){delimiter}\"" in html:
        raise ValueError(f"{source_path.name} contains the raw string delimiter")

    return (
        f"// Generated by tools/embed_dashboard.py from {source_path.relative_to(PROJECT_DIR)}.\n"
        f"const char {symbol_name(source_path)}[] PROGMEM = R\"{delimiter}(\n"
        f"{html}\n"
        f"){delimiter}\";\n"
    )


def build_header(target_path):
    pages = page_files()
    page_sources = "\n".join(build_page(page) for page in pages)
    route_checks = []
    for page in pages:
        route_match = " || ".join(f'path == "{route}"' for route in routes_for(page))
        route_checks.append(f"  if ({route_match}) {{ return {symbol_name(page)}; }}")

    header = (
        "#pragma once\n\n"
        "#include <Arduino.h>\n\n"
        f"{page_sources}"
        "inline const char *webPageForPath(const String &path)\n"
        "{\n"
        f"{chr(10).join(route_checks)}\n"
        "  return nullptr;\n"
        "}\n"
    )
    target_path.write_text(header, encoding="utf-8")


build_header(TARGET)
